name: UNIFIED2-CI-DEV-DO

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DEPLOYMENT_ENV: dev
      AWS_REGION: ap-south-1
      WHL_BUILD_NAME: unified2-1.0.0
      ECS_SERVICE_NAME: infinity-unified2
      DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
      ECS_CLUSTER_NAME: ecs-infinity-ap1-dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: develop

      - name: buiding docker
        run: |
          BUILD_TIME=$(date "+%d-%B-%Y %H:%M:%S (UTC)")

          sed -i -e "s/{BUILD_TIME}/$BUILD_TIME/" unified/modules/health-check/application.py
          sed -i -e "s/{BUILD_NUMBER}/${{ steps.tag_version.outputs.new_tag }}/" unified/modules/health-check/application.py

          cat << EOF >> Dockerfile
          FROM python:3.9-slim-buster

          LABEL maintainer="satyabrata.swain@500apps.com"

          RUN apt-get update -y \
            && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            supervisor \
            awscli


          COPY requirements.txt /requirements.txt


          RUN /usr/local/bin/python -m pip install --upgrade pip \
            && pip install --no-cache-dir -r requirements.txt \
            && mkdir -p /root/unified2

          ADD unified /root/unified2/unified

          WORKDIR /root/unified2

          CMD ["waitress-serve", "--listen=*:80", "unified:unified"]
          EOF

          docker build -t 500apps/images:unified2 .

          echo ${{ env.DOCKER_SECRET }} | docker login --username 500apps --password-stdin

          docker push 500apps/images:unified2
        shell: bash

      - name: setup SSH Keys and known_hosts
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PEM }}"  
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: redeploying service over ssh
        run: |
          ssh -o StrictHostKeyChecking=no root@159.65.152.90 <<'ENDSSH'
          echo ${{ env.DOCKER_SECRET }} | docker login --username 500apps --password-stdin
          docker rm -f $(docker ps | grep "unified2" | awk -F" " '{ print $1 }')
          docker pull 500apps/images:unified2
          docker run --rm --name unified2 --log-opt max-size=50m -p 8091:80 -d 500apps/images:unified2 
          ENDSSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock